In [ ]:
# Task: Exploratory Data Analysis

import pandas as pd
import matplotlib.pyplot as plt

# Load the data
url = 'nvidia_stock_2015_to_2024.csv'
df = pd.read_csv(url)
df

,Unnamed: 0,date,open,high,low,close,adjclose,volume
0,0,2015-01-02,0.503250,0.507000,0.495250,0.503250,0.483218,113680000
1,1,2015-01-05,0.503250,0.504750,0.492500,0.494750,0.475056,197952000
2,2,2015-01-06,0.495500,0.496000,0.479250,0.479750,0.460654,197764000
3,3,2015-01-07,0.483250,0.487500,0.477000,0.478500,0.459453,321808000
4,4,2015-01-08,0.484000,0.499500,0.483750,0.496500,0.476737,283780000
...,...,...,...,...,...,...,...,...
2364,2364,2024-05-24,104.448997,106.474998,103.000000,106.469002,106.460258,429494000
2365,2365,2024-05-28,110.244003,114.939003,109.883003,113.901001,113.891647,652728000
2366,2366,2024-05-29,113.050003,115.491997,110.901001,114.824997,114.815567,557442000
2367,2367,2024-05-30,114.650002,115.819000,109.663002,110.500000,110.490921,487350000
2368,2368,2024-05-31,112.519997,112.717003,106.940002,109.633003,109.624001,613263000

In [ ]:
import os

# Checking for Null Values
if df.isnull().sum().sum() == 0:
  print("Dataset doesn't contain any null values!")

# Create a copy of the DataFrame to avoid modifying the original
df_cleaned = df.copy()

df_cleaned['date'] = pd.to_datetime(df_cleaned['date'])
# Drop the unnecessary column
df_cleaned = df_cleaned.drop('Unnamed: 0', axis=1)
df_cleaned

# Save Cleaned Data
# Define the folder and file path
folder_path = 'processed'
file_name = 'nvidia_stock_cleaned.csv'

# Save the cleaned DataFrame to the folder
file_path = os.path.join(folder_path, file_name)
df_cleaned.to_csv(file_path, index=False)

print(f"Cleaned DataFrame saved to {file_path}")

Dataset doesn't contain any null values!
Cleaned DataFrame saved to processed/nvidia_stock_cleaned.csv

Since there were no null values to be found and the unnecessary columns have been removed, this dataset is cleaned. Before we finish, it is important to check that our data is in the correct data type to work with.

In [ ]:
df_cleaned.dtypes

date        datetime64[ns]
open               float64
high               float64
low                float64
close              float64
adjclose           float64
volume               int64
dtype: object